services:
  niu-dining-hall-discord-bot:
    build: .
    container_name: niu-dining-hall-discord-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /mnt/Docker_Apps/NIU-Dining-Hall-Discord-Bot:/app
    environment:
      - DINING_BOT_TOKEN=AbunchOFnumbersANDletters
      - CHANNEL=12345678
      - CHECK_PATTERSON_BREAKFAST=1
      - CHECK_PATTERSON_LUNCH=1
      - CHECK_PATTERSON_DINNER=1
      - CHECK_NEPTUNE_BREAKFAST=1
      - CHECK_NEPTUNE_LUNCH=1
      - CHECK_NEPTUNE_DINNER=1
      - WHEN_TO_CHECK=8
      - KEYWORDSTOCHECK= ["food1", "food2"]
      - TZ=America/Chicago

