services:
  niu-dining-hall-discord-bot:
    build: .
    container_name: niu-dining-hall-discord-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /mnt/Docker_Apps/NIU-Dining-Hall-Discord-Bot:/app
    environment:
      - DINING_BOT_TOKEN=
      - CHANNEL= 
      - CHECK_PATTERSON_LUNCH=
      - CHECK_PATTERSON_DINNER=
      - CHECK_NEPTUNE_LUNCH=
      - CHECK_NEPTUNE_DINNER=
      - WHEN_TO_CHECK=
      - KEYWORDSTOCHECK=
